<?php if (! defined('ABSPATH')) { exit; } ?>
<article class="ec-card ec-full">
	<div class="ec-card-head"><div><p class="ec-eyebrow">Step 3</p><h2>ผูก key เดียวกับหลาย licence</h2><p>เลือก key ก่อน แล้วค่อยติ๊กเลือก licence ได้หลายรายการจาก pool เดียวกัน และกด assign จากหน้าจอเดียวครับ</p></div><div class="ec-badge">Multi-assign workflow</div></div>
	<div class="ec-assignment-grid">
		<div class="ec-assignment-main">
			<div class="ec-fields two" style="margin-top:0;"><div class="ec-field"><label for="ecSelectKey">Select APPTOOK Key</label><select id="ecSelectKey" class="ec-input"><?php if (empty($available_keys)) : ?><option value="">No key found</option><?php else : foreach ($available_keys as $key) : ?><option value="<?php echo esc_attr((string) $key['id']); ?>"><?php echo esc_html((string) $key['key_code']); ?><?php echo ! empty($key['status']) ? ' (' . esc_html((string) $key['status']) . ')' : ''; ?></option><?php endforeach; endif; ?></select></div><div class="ec-field"><label for="ecFilterLicence">Search / Filter Licence</label><input id="ecFilterLicence" class="ec-input" type="text" placeholder="Search by code, note, or token"></div></div>
			<div class="ec-field"><label>Select Licence(s)</label><div class="ec-checkbox-list ec-licence-select-list" id="ecLicenceList"><?php if (empty($licences)) : ?><div class="ec-mini-note">ยังไม่มี licence ในฐานข้อมูล กรุณา import ข้อมูลก่อน</div><?php else : foreach ($licences as $licence) : ?><div class="ec-licence-item"><label class="ec-checkbox-item"><input type="checkbox" value="<?php echo esc_attr((string) $licence['id']); ?>"><span><strong><?php echo esc_html($licence['token']); ?></strong><small><?php echo esc_html((string) $licence['duration_days']); ?> days • <?php echo esc_html((string) $licence['token_limit']); ?> tokens • <?php echo esc_html((string) $licence['status']); ?></small></span></label><button class="ec-btn ec-btn-soft ec-delete-licence" type="button" data-id="<?php echo esc_attr((string) $licence['id']); ?>">Delete</button></div><?php endforeach; endif; ?></div><div class="ec-help">ติ๊กเลือกได้หลายรายการโดยไม่ต้องกด Ctrl / Cmd</div></div>
		</div>
		<div class="ec-assignment-side"><div class="ec-mini-note">System assigns licences automatically when you click assign, so there is no priority field to configure in the first version.</div><div class="ec-mini-note">Recommended flow: 1) choose a key 2) filter licences 3) tick multiple items 4) click assign 5) use unassign or replace when you need to adjust the mapping.</div><div class="ec-actions compact"><button class="ec-btn ec-btn-primary" id="ecAssignSelected" style="flex:1" type="button">Assign Selected</button><button class="ec-btn ec-btn-soft" id="ecRefreshList" style="flex:1" type="button">Refresh List</button></div><div class="ec-actions compact"><button class="ec-btn ec-btn-soft" id="ecUnassignSelected" style="flex:1" type="button">Unassign Selected</button><button class="ec-btn ec-btn-soft" id="ecReplaceSelected" style="flex:1" type="button">Replace Selected</button></div></div>
	</div>
</article>
